dataset: "seandi/cord-v2-token-classification"
# dataset: "tmp/dataset/cord-v2-token-classification"

split: "testazure"                           

checkpoint: "seandi/layoutlmv3-cord-v2-token-classification"
# checkpoint: "tmp/experiments/layoutlmv3/train-xxxxxx/last"