project: cord/layoutlmv3
task: train

dataset: "seandi/cord-v2-token-classification"
# dataset: "tmp/dataset/cord-v2-token-classification"

batch: 16 #8
lr: 0.00005
max_steps: 4000 # 8000
log_steps: 100
val_split: validation
val_steps: 400
checkpoint_steps: 2000
mixed_precision: "tf32" # "fp16" or "no"
output_folder: tmp/experiments/layoutlmv3
upload_model: true